# BUILD PART
FROM node:18-slim AS build

WORKDIR /app

COPY package.json ./

RUN yarn install

COPY . .
RUN yarn run build

# SERVE PART
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
